version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: npm run dev -- --host
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: .
        target: /app